### ISSUE TITLE
Request: Change Theme/Colors

### ISSUE THREAD

**Issue by j-leow** [alexandrubuncea/figma-annotate-design#1]
Hi Alexandru, I LOVE this plugin. It really helps me with making quick annotations. I would like to request being able to change the color of the annotations, if possible. At the moment, I just unlock the layer and make the changes there but it would be cool if I could do that from the plugin itself. Not sure if you're still actively supporting this plugin or not but thought I'd ask. Thank you!

**Comment by alexandrubuncea** [comment]
Hello,

Are you thinking sort of a dark theme / light theme switcher for the annotation itself?

If yes, I have this in my plans and I will explore it.

**Comment by j-leow** [comment]
Hi @alexandrubuncea thanks for responding! So, right now, the text bubble and line with dot shows up in black, and text is white. I was wondering if it'll be possible for me to choose the text and bg color. My team and I use a shade of magenta for comments, so what I did after using your plugin is to unlock the annotation layers and just switch the text/bg colors. Hope that makes sense!

**Comment by alexandrubuncea** [comment]
I know this took me a very long time, but I finally managed to push an update for this and included more colors. Hope it's useful. 

If you encounter any issues please let me know!
