### ISSUE TITLE
Request: Lock/Unlock annotations

### ISSUE THREAD

**Issue by jlopzp07** [alexandrubuncea/figma-annotate-design#2]
Hey Alexandru,

Your plugin is awesome and pretty straightforward and I loved it. It has helped me save a lot of time creating components and arrows and all that stuff.

I just wanted to recommend (if you haven't thought about it) that it would be good to have a switch or a checkbox that allows us to decide whether we want to have the annotations locked or not, cause it happens that sometimes I need to move a whole frame to a different position and I need to go to the tree and search for the annotations and unlock them. It's not hard of course but if your plugin saves us that much time already, this surely will bust it to another level. 

Hope you find this helpful and thank you for your plugin!

**Comment by alexandrubuncea** [comment]
Hi, I know it took me a long time, but I pushed an update for this that doesn't lock annotations anymore. Now you can also use different colors and also show the author's name.

Let me know if you encounter any issues!
